name: karthick_mugunthan_s_s_application3
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=3.3.2 <4.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_bloc: ^8.1.3
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  equatable: ^2.0.5
  outline_gradient_button: ^2.0.1+1
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Tourney
      fonts: 
        - asset: assets/fonts/TourneyRomanRegular.ttf
          weight: 400
    - family: Sen
      fonts: 
        - asset: assets/fonts/SenRegular.ttf
          weight: 400
